[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim' build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'vim-scripts/MultipleSearch'

[[plugins]]
repo = 'hewes/unite-gtags'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'ujihisa/unite-rake'

[[plugins]]
repo = 'ujihisa/unite-locate'

[[plugins]]
repo = 'rgarver/Kwbd.vim'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'vim-scripts/BufOnly.vim'

[[plugins]]
repo = 'tpope/vim-dispatch'


